# Generated by Django 3.0.8 on 2020-07-29 07:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 7, 4, 40, 46962, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 7, 4, 40, 47259, tzinfo=utc)),
        ),
    ]
